accum_batch: 1
additional_feats: true
atom_type_masking: true
atoms_categorical: true
backprop_local: false
batch_size: 8
beta_max: 0.02
beta_min: 0.0001
bond_guidance_model: false
bond_model_guidance: false
bond_prediction: false
bonds_categorical: true
build_mol_with_addfeats: false
calculate_energy: false
ckpt_bond_model: null
ckpt_energy_model: null
ckpt_polarizabilty_model: null
context_mapping: false
continuous: false
continuous_param: data
cutoff_global: 10.0
cutoff_local: 7.0
data_info_path: /home/qcx679/hantang/UAAG2/data/full_graph/statistic.pkl
dataset: drugs
dataset_root: '----'
detect_anomaly: false
diffusion_pretraining: false
dropout_prob: 0.3
edge_mp: false
edim: 32
edim_latent: 32
ema_decay: 0.9999
energy_loss: l2
energy_model_guidance: false
energy_training: false
eps_min: 0.001
eval_freq: 1.0
fully_connected: true
gamma: 0.975
gpus: 1
grad_clip_val: 10.0
guidance_scale: 0.0001
id: Full_mask_5_virtual_node_mask_token_atomic_only_mask_diffusion_0917
inference_batch_size: 32
latent_detach: false
latent_dim: null
latent_layers: 7
latentmodel: diffusion
lc_atoms: 0.4
lc_bonds: 2.0
lc_charges: 1.0
lc_coords: 3.0
lc_mulliken: 1.5
lc_wbo: 2.0
ligand_pocket_interaction: false
load_ckpt: /home/qcx679/hantang/UAAG2/3DcoordsAtomsBonds_0/runFull_mask_5_virtual_node_mask_token_atomic_only_mask_diffusion_0915/last.ckpt
load_ckpt_from_pretrained: null
local_edge_attrs: false
local_global_model: false
logger_type: wandb
loss_weighting: snr_t
lr: 0.0005
lr_cooldown: 5
lr_factor: 0.75
lr_frequency: 5
lr_min: 5.0e-05
lr_patience: 20
lr_scheduler: reduce_on_plateau
lr_step_size: 10000
mask_rate: 0.0
max_num_conformers: 5
max_num_neighbors: 128
max_time: null
max_virtual_nodes: 5
no_h: false
noise_scheduler: cosine
num_bond_classes: 5
num_charge_classes: 6
num_context_features: 0
num_epochs: 5000
num_layers: 7
num_layers_latent: 7
num_test_graphs: 10000
num_workers: 4
optimizer: adam
pdbbind_weight: 10.0
pocket_noise: false
pocket_noise_scale: 0.01
polarizabilty_model_guidance: false
precision: 32
prior_beta: 1.0
properties_list: []
property_prediction: false
property_training: false
rbf_dim: 32
regression_property: polarizability
remove_hs: false
save_dir: /home/qcx679/hantang/UAAG2/3DcoordsAtomsBonds_0
save_xyz: false
sdim: 256
sdim_latent: 256
seed: 42
select_train_subset: false
snr_clamp_max: 1.5
snr_clamp_min: 0.05
test_interval: 5
test_save_dir: /home/qcx679/hantang/UAAG2/3DcoordsAtomsBonds_0
test_size: 32
timesteps: 500
train_size: 0.99
use_absorbing_state: false
use_adaptive_loader: true
use_cross_product: false
use_ligand_dataset_sizes: false
use_pos_norm: false
use_qm_props: false
val_size: 5000
variational_sampling: false
vdim: 64
vdim_latent: 64
vector_aggr: mean
virtual_node: 1
weight_decay: 0.9999
